spring.kafka.consumer.properties.spring.json.trusted.packages: '*'
spring.cloud.stream:
  function: numbersService
  bindings:
    numbersService-in-0:
      destination: formatedNumbers
  kafka:
    bindings:
      numbersService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092