spring.kafka.consumer.properties.spring.json.trusted.packages: '*'
spring.cloud.stream:
  function:
    definition: numbersprocessed
  bindings:
    numbersprocessed-in-0:
      destination: numbersdata
    numbersprocessed-out-0:
      destination: formatedNumbers
  kafka:
    bindings:
      numbersprocessed-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      numbersprocessed-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
     brokers:
       - localhost:9091
       - localhost:9092
